### ISSUE TITLE
Add test for #16.

### ISSUE THREAD

**Issue by ryneeverett** [ryneeverett/git-regress#18]
Add test for #16.

Wait for #15.

**Comment by ryneeverett** [comment]
Oops, the script probably isn't working like I thought it was:

```
$ python test.py -d term TestTracked.test_modifying_nested_files
Saved working directory and index state WIP on master: 486874d Add nested file.
HEAD is now at 486874d Add nested file.
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Note: checking out 'HEAD^'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at b94ea06... Trivial. Implement pointlessness.
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was b94ea06... Trivial. Implement pointlessness.
HEAD is now at 629e8b6... Trivial
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was 629e8b6... Trivial
HEAD is now at 4733c5c... Trivial. Implement pointlessness after regression.
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was 4733c5c... Trivial. Implement pointlessness after regression.
HEAD is now at 92a6910... Trivial
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was 92a6910... Trivial
HEAD is now at dfd1a68... Regression.
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was dfd1a68... Regression.
HEAD is now at b97bd59... Trivial. Implement pointlessness.
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was b97bd59... Trivial. Implement pointlessness.
HEAD is now at 53c4609... Trivial
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was 53c4609... Trivial
HEAD is now at 934db22... Trivial
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was 934db22... Trivial
HEAD is now at ed10296... Trivial. Implement pointlessness.
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was ed10296... Trivial. Implement pointlessness.
HEAD is now at a12c78e... Add test file.
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was a12c78e... Add test file.
HEAD is now at b68a40d... Trivial. Implement pointlessness.
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was b68a40d... Trivial. Implement pointlessness.
HEAD is now at 005972c... Trivial
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
Previous HEAD position was 005972c... Trivial
HEAD is now at 53d8ba4... Initial commit.
cat: subdir/nested.txt: No such file or directory
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: [: numeric argument required
../resources/git-regress-tmp-test_modifying_nested_files.sh: line 3: return: can only `return' from a function or sourced script
error: pathspec 'HEAD^' did not match any file(s) known to git.
---------------------------------------------------------------------------------------------------------------------------------------------
REPO EXHAUSTED: Command Never Succeeded
---------------------------------------------------------------------------------------------------------------------------------------------
Previous HEAD position was 53d8ba4... Initial commit.
Switched to branch 'master'
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   subdir/nested.txt
    modified:   test.py

no changes added to commit (use "git add" and/or "git commit -a")
E
======================================================================
ERROR: test_modifying_nested_files (__main__.TestTracked)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 212, in test_modifying_nested_files
    py_test=False)
  File "test.py", line 120, in runRegress
    raise Exception('In debug mode, assertions are not tested.')
Exception: In debug mode, assertions are not tested.

----------------------------------------------------------------------
Ran 1 test in 3.607s

FAILED (errors=1)
```

**Comment by ryneeverett** [comment]
Fixed those errors, so now the question is why the test fails.

**Comment by ryneeverett** [comment]
Temporary files only get created for file paths passed as parameters, so `nested.txt` is just getting stashed.
